/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Camil
 */
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;

public class Client extends javax.swing.JFrame {
	
    private JFrame frame;
    private JTextField textField;
    public static JLabel lblInfo = new JLabel();
    JTextArea txtAreaWords;
    JLabel lblTrRec;
    JLabel lblScore2;
	
    private Socket socket;
    private Scanner in;
    private PrintWriter out;
    
    int index = 0;
    protected String chosenWordsArray[];
    /**
     * Creates new form Client
     */
    public Client() throws IOException {
        //initComponents();
        InitNewComps();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InitNewComps() throws IOException{
        System.out.println("Usao u play methodu");
	socket = new Socket("localhost", 59898);
	in = new Scanner(socket.getInputStream());
        out = new PrintWriter(socket.getOutputStream(), true);
		
	frame = new JFrame();
        frame.setTitle("Typing Wars");
	frame.setBounds(100, 100, 639, 450);
	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	frame.getContentPane().setLayout(null);
		
        JPanel panel = new JPanel();
        panel.setBounds(0, 10, 616, 403);
	frame.getContentPane().add(panel);
        panel.setLayout(null);
                
	JLabel lblNewLabel = new JLabel("VI:");
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 14));
	lblNewLabel.setBounds(10, 0, 126, 29);
        panel.add(lblNewLabel);
		
	JLabel lblProtivnik = new JLabel("Potrebno vreme:");
        lblProtivnik.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblProtivnik.setBounds(10, 39, 126, 29);
        panel.add(lblProtivnik);

        JLabel lblScore1 = new JLabel("");
        lblScore1.setBorder(new LineBorder(new Color(0, 0, 0), 2));
        lblScore1.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 15));
        lblScore1.setBounds(146, 0, 191, 29);
        panel.add(lblScore1);

        lblScore2 = new JLabel("0");
        lblScore2.setBorder(new LineBorder(new Color(0, 0, 0), 2));
        lblScore2.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 15));
        lblScore2.setBounds(146, 39, 191, 29);
        panel.add(lblScore2);

        lblInfo.setBackground(new Color(135, 206, 235));
        lblInfo.setHorizontalAlignment(SwingConstants.CENTER);
        lblInfo.setFont(new Font("Tahoma", Font.BOLD, 19));
        lblInfo.setForeground(new Color(255, 99, 71));
        lblInfo.setBounds(389, 0, 174, 67);
        panel.add(lblInfo);


        JLabel lblNewLabel_3 = new JLabel("Nakon ispravno upisane reci pritisnite 'SPACE'");
        lblNewLabel_3.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lblNewLabel_3.setBounds(50, 256, 261, 22);
        panel.add(lblNewLabel_3);

        lblTrRec = new JLabel();
        lblTrRec.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblTrRec.setHorizontalAlignment(SwingConstants.CENTER);
        lblTrRec.setBounds(214, 343, 184, 29);
        //lblTrRec.setText(words[0].toLowerCase().replace(" ", ""));
        panel.add(lblTrRec);

        textField = new JTextField("Waiting to connect to server...");
        textField.setEditable(false);
        textField.setFont(new Font("Tahoma", Font.PLAIN, 15));

        /*EventListener za TextField koja slusa da li je kliknut space*/
        textField.addKeyListener(new KeyAdapter() {
                public void keyPressed(KeyEvent e) {
                        if(e.getKeyCode() == KeyEvent.VK_SPACE) {
                            String typedWord = textField.getText().replace(" ", "");
                            out.println(typedWord);
                            String res;
                            res = in.nextLine();
                            if(res != null && !res.equals("")) {
                                if(res.startsWith("SCORE")) {
                                    textField.setText("");
                                    lblScore1.setText(res.substring(6));
                                    lblInfo.setText("TACNO!");
                                    index += 1;
                                    if(index < 20)
                                        lblTrRec.setText(chosenWordsArray[index]); 
                                }
                                else if(res.startsWith("WRONG")){
                                    lblInfo.setText("GRESKA!");
                                }
                                else{
                                    int secBr = 0;
                                    int minBr = 0;
                                    System.out.println("Primio TIME");
                                    lblInfo.setText("KRAJ!");
                                    secBr =  Integer.parseInt(res.substring(5)) / 1000;
                                    while(secBr > 59){
                                        secBr -= 60;
                                        minBr += 1;
                                    }
                                    lblScore1.setText(lblScore1.getText() + "/");
                                    lblScore2.setText("0" + minBr + " : " + secBr);        
                                    textField.setEditable(false);        
                                    textField.setEnabled(false);
                                    try {
                                        socket.close();
                                    } catch (IOException ex) {
                                        Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                }
                            }
                        }
                }
        });
        textField.setHorizontalAlignment(SwingConstants.CENTER);
        textField.setBounds(50, 288, 509, 50);
        panel.add(textField);
        textField.setColumns(10);

        txtAreaWords = new JTextArea();
        txtAreaWords.setWrapStyleWord(true);
        txtAreaWords.setTabSize(3);
        txtAreaWords.setRows(5);
        txtAreaWords.setFont(new Font("Monospaced", Font.BOLD, 16));
        txtAreaWords.setLineWrap(true);
        txtAreaWords.setEditable(false);
        txtAreaWords.setBounds(10, 89, 606, 157);
        panel.add(txtAreaWords);
		
    }
    
    public void play() throws Exception{
        try {
            for(int i = 0; i<2; i++) {
                if(in.hasNextLine()){
                    String serverInput = in.nextLine();
                    if(serverInput.startsWith("START")) { 
                            System.out.println("Pali se program");
                            textField.setEditable(true);
                            textField.setText("");
                            lblTrRec.setText(this.chosenWordsArray[index]);
                    }
                    else {
                            txtAreaWords.setText(serverInput.toString());
                            this.chosenWordsArray = serverInput.split(" ");
                            System.out.println("Ubacio u chosenWordsArray");
                    }
                }
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        } finally {
            //socket.close();
            //frame.dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Client window;
                try {
                    window = new Client();
                    window.frame.setVisible(true);
                    window.frame.setResizable(false);
                    window.play();
                } catch (IOException ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
